name: geolocation_poc
description: Geolocation POC

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  intl: ^0.19.0
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_secure_storage: ^6.0.0
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_core_web: ^2.6.0
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.0.1
  screenshot: ^2.1.0
  flutter_svg: ^1.1.5
  syncfusion_flutter_datepicker: ^20.3.50
  flutter_multi_formatter: ^2.8.0
  flutter_keyboard_visibility: ^5.4.0
  font_awesome_flutter: ^10.2.1
  dots_indicator: ^2.1.0
  currency_text_input_formatter: ^2.1.7
  pull_to_refresh: ^2.0.0
  camera: ^0.10.5+5
  animated_text_kit: ^4.2.2
  credit_card_type_detector: ^3.0.0
  qr_flutter: ^4.1.0
  uuid: ^3.0.7
  google_maps_flutter: ^2.3.1
  geocoding: ^2.0.5
  url_launcher: ^6.1.6
  dotted_border: ^2.0.0+2
  pin_code_fields: ^7.4.0
#  flutter_stripe: 9.2.0
  flutter_dotenv: ^5.0.2
  credit_card_validator: ^2.1.0
  package_info_plus: ^4.0.1
  nfc_manager: ^3.2.0
  shimmer: ^2.0.0
  easy_localization: ^3.0.1
  flutter_inappwebview: ^5.5.0+3
  permission_handler: ^11.0.1
  bugsnag_flutter: ^3.0.0
  intercom_flutter: ^7.8.2
  avatar_glow: ^2.0.2
#  flutter_nfc_kit: ^3.3.1
  ndef: ^0.3.1
  uni_links: ^0.5.1
  translit: ^2.0.1
  google_mlkit_text_recognition: ^0.8.1
  map_launcher: ^2.5.0+1
  video_player: ^2.7.0
  youtube_player_flutter: ^8.1.2
  collection: ^1.17.1
  share_plus: ^7.1.0
  flutter_avif: ^1.4.0
  aws_s3_upload: ^1.5.0
  path_provider: ^2.0.2
  geolocator: any
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: any
  flutter_launcher_icons: ^0.13.1
  lint: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_cool.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon_cool.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon_cool.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon_cool.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_cool.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/

  fonts:
    - family: Graphik
      fonts:
        - asset: fonts/GraphikThin.otf
          weight: 100
        - asset: fonts/GraphikExtraLight.otf
          weight: 200
        - asset: fonts/GraphikLight.otf
          weight: 300
        - asset: fonts/GraphikRegular.otf
          weight: 400
        - asset: fonts/GraphikMedium.otf
          weight: 500
        - asset: fonts/GraphikSemiBold.otf
          weight: 600
        - asset: fonts/GraphikBold.otf
          weight: 700
        - asset: fonts/GraphikBlack.otf
          weight: 800
        - asset: fonts/GraphikSuper.otf
          weight: 900
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik-Black.ttf
          weight: 900
