name: Flutter Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
       flutter-version: '3.24.2'  

    - name: Clear Flutter/Dart Cache
      run: |
        flutter clean
        rm -rf ~/.pub-cache

    - name: Check Flutter and Dart Versions
      run: |
        flutter --version
        dart --version

    - name: Install dependencies
      run: flutter pub get

    - name: Extract version from pubspec.yaml
      id: extract_version
      run: |
        VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //g' | sed 's/+.*//g')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build APK
      run: flutter build apk --release

    - name: Build AAB
      run: flutter build appbundle --release

    - name: Rename APK and AAB with version number
      run: |
        mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/app-release-$VERSION.apk
        mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/app-release-$VERSION.aab

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-${{ env.VERSION }}.apk
        path: build/app/outputs/apk/release/app-release-${{ env.VERSION }}.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-release-${{ env.VERSION }}.aab
        path: build/app/outputs/bundle/release/app-release-${{ env.VERSION }}.aab
